Added ahoy command and env variables to download CKAN logs

diff --git a/.ahoy.yml b/.ahoy.yml
--- a/.ahoy.yml
+++ b/.ahoy.yml
@@ -150,3 +150,32 @@ commands:
       fi
       open $SITE_URL
 
+  download-ckan-logs:
+    usage: Download CKAN logs
+    cmd: |
+      if [ -z "$AZURE_FILE_SHARE_URL" ] || [ -z "$AZURE_FILE_SHARE_SAS_TOKEN" ]; then
+        echo "AZURE_FILE_SHARE_URL or AZURE_FILE_SHARE_SAS_TOKEN is not set"
+        exit 1
+      fi
+      echo "Downloading ckan_logs from:$AZURE_FILE_SHARE_URL"
+      LOG_FILE="ckan.log"
+      FULL_URL="$AZURE_FILE_SHARE_URL/ckan_logs/$LOG_FILE?$AZURE_FILE_SHARE_SAS_TOKEN"
+      echo "Downloading ckan.log:$FULL_URL"
+      curl -L -o dbca/ckan_logs/ckan.log "$FULL_URL"
+      echo "Downloading ckan-crons-jobs.log"
+      LOG_FILE="ckan-crons-jobs.log"
+      FULL_URL="$AZURE_FILE_SHARE_URL/ckan_logs/$LOG_FILE?$AZURE_FILE_SHARE_SAS_TOKEN"
+      curl -L -o dbca/ckan_logs/ckan.log "$FULL_URL"
+      echo "Downloading ckan-worker.log"
+      LOG_FILE="ckan-worker.log"
+      FULL_URL="$AZURE_FILE_SHARE_URL/ckan_logs/$LOG_FILE?$AZURE_FILE_SHARE_SAS_TOKEN"
+      curl -L -o dbca/ckan_logs/ckan.log "$FULL_URL"
+      echo "Downloading nginx access log"
+      LOG_FILE="nginx_access.log"
+      FULL_URL="$AZURE_FILE_SHARE_URL/ckan_logs/$LOG_FILE?$AZURE_FILE_SHARE_SAS_TOKEN"
+      curl -L -o dbca/ckan_logs/ckan.log "$FULL_URL"
+      echo "Downloading nginx error log"
+      LOG_FILE="nginx_access.log"
+      FULL_URL="$AZURE_FILE_SHARE_URL/ckan_logs/$LOG_FILE?$AZURE_FILE_SHARE_SAS_TOKEN"
+      curl -L -o dbca/ckan_logs/ckan.log "$FULL_URL"
+      echo "CKAN logs downloaded to dbca/ckan_logs"
